# Generated by Django 4.2.1 on 2023-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabletest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
