# Generated by Django 4.2.1 on 2023-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabletest", "0009_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
